### ISSUE TITLE
Print Error

### ISSUE THREAD

**Issue by iCodexDev** [Shiranuit/LuaCoro#4]
Hello , can you please check why in an async function didn't show which line has error.

for example in line 34 we have something like ``local x = a.y.z`` so if ``a`` be a string in normal function print which line has error and we can fix that but in async function it's not print on terminal which line has error.

Thank you .

**Comment by Shiranuit** [comment]
You probably forgot to catch the error.
When an error occurs in an async function all the async function that awaited the errored async function will stop and propagate the error that occured in the awaited promise.

I will give you multiple examples if you're not familiar with this concept:

Like you said this example does not show anything
```lua
local coro = require('coro')

local myFunc = coro.async(function(a)
  local x = a.y
  return x
end)

local main = coro.async(function()
  local result = coro.await(myFunc())
  print(result)
end)

main()
coro.run()
```

This is because unlike with standard functions, if an error occurs in a promise it doesn't mean your program will stop, only the promise and those who awaited it will have an error and stop being executed.

In this example if `myFunc` has an error, the `main` function will also be errored because it depend on the result of `myFunc` since the function is awaited.

This is where you should be sure the promise will never throw or you should add a catch handler that is going to receive the error and continue the flow of execution.

Here I add a `catch` handler on the promise returned by the `main` function and print the error.

```lua
local coro = require('coro')

local myFunc = coro.async(function(a)
  local x = a.y
  return x
end)

local main = coro.async(function()
  local result = coro.await(myFunc())
  print(result)
end)

main():catch(function(err)
  print(err) -- error.lua:9: error.lua:4: attempt to index a nil value (local 'a')
end)
coro.run()
``` 

You could also have put the `catch` handler way before, directly on the `myFunc` function to prevent the main from being stopped in case of an error.

```lua
local coro = require('coro')

local myFunc = coro.async(function(a)
  local x = a.y
  return x
end)

local main = coro.async(function()
  local result = coro.await(myFunc():catch(function(err)
    print(err) -- error.lua:4: attempt to index a nil value (local 'a')
  end))
  print(result) -- nil
end)

main()
coro.run()
``` 

An other thing that you could do with `catch` is returning a new value when an error occurs like so

```lua
local coro = require('coro')

local myFunc = coro.async(function(a)
  local x = a.y
  return x
end)

local main = coro.async(function()
  local result = coro.await(myFunc():catch(function(err)
    return 42
  end))
  print(result) -- 42
end)

main()
coro.run()
``` 

In this case if `myFunc` is errored, the `catch` handler will return the value `42` so `result` will be equal to `42`, if no error had occured then the resulting value would have been what `myFunc` returned.

One last thing, if you forgot to catch an async function you could use the `coro.onUnhandledRejection` to register a callback
that is called whenever an error occurs in an async function that has no `catch` handler.

Keep in mind that this handler is only here to help you find where a crashed occured if you forgot to put `catch` handler, your whole program should not rely on this to handle exceptions.

```lua
local coro = require('coro')

coro.onUnhandledRejection(function(err)
  print(err) -- error.lua:13: error.lua:8: attempt to index a nil value (local 'a')
end)

local myFunc = coro.async(function(a)
  local x = a.y
  return x
end)

local main = coro.async(function()
  local result = coro.await(myFunc())
  print(result)
end)

main()
coro.run()
``` 

### I updated the library so the error stack is properly constructed, there was some missing informations earlier

**Comment by Shiranuit** [comment]
> thank you , i use coro.onUnhandledRejection as you say and print error work fine but one more thing that error will be print twice each time that aysnc function call.

Yes I've also noticed this, I updated the library and this should be fixed now

**Comment by Shiranuit** [comment]
I will closed it for now, feel free to open a new issue if there is still something wrong
